#!/bin/bash

    # echo each command and exit upon any failures.
set -ex


## Arguments ##

VER=$1
if ! [ "$VER" ]
then
    echo "Error: no version specified" >&2
    exit 1
fi
shift


## Setup ##

ROOT=$(dirname $(dirname $0))


## Main release ##

ln -s $ROOT mkvreader-${VER}
tar -chf mkvreader-${VER}.tar --exclude=.git mkvreader-${VER}
xz mkvreader-${VER}.tar
md5sum mkvreader-${VER}.tar.xz > mkvreader-${VER}.tar.xz.md5
rm mkvreader-${VER}


## Cleanup ##

rm -rf mkvreader-${VER}
